services:
  - type: web
    name: checkgdvut-backend
    env: node
    buildCommand: npm install
    startCommand: node src/server.js
    plan: free
    envVars:
      - key: TOKEN
        value: <TOKEN_CỦA_BẠN>
      - key: API_KEY
        value: <API_KEY_FIREBASE>
      - key: AUTH_DOMAIN
        value: <AUTH_DOMAIN_FIREBASE>
      - key: PROJECT_ID
        value: <PROJECT_ID_FIREBASE>
